---
title: "Summary stats of prioritized candidates"
author: "Fabrício Almeida-Silva"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE, 
                      message = FALSE,
                      tidy.opts = list(width.cutoff = 60),
                      tidy = TRUE)
```

## Functional classification of candidates

The file "all_mined_candidates" was manually modified to include descriptions for all genes and their role in plant defense. Let's plot data now.

```{r candidate_classification_stats}
library(tidyverse)
library(here)
cpal <- c("darkgoldenrod3", "dimgrey", "darkgreen")

all_cand_des <- read.csv(here("products", "tables",
                              "all_mined_candidates_and_description.txt"),
                         header=TRUE, sep="\t")

freq_abs_cand <- all_cand_des %>%
  janitor::tabyl(Role, Species) %>%
  mutate(Role = stringr::str_replace_all(Role, "SM metabolism", 
                                         "Specialized metabolism")) %>%
  reshape2::melt()

freq_cand <- freq_abs_cand %>%
  group_by(variable) %>%
  mutate(percentage = value / sum(value))

p_cand <- ggplot(freq_cand) +
  geom_bar(aes(x=percentage, y=Role, fill = variable), stat="identity",
           show.legend=FALSE) +
  ggplot2::scale_fill_manual(values = cpal) +
  facet_wrap(~variable, ncol=5) +
  theme_bw() +
  labs(x="Relative frequency", y="")

ggsave(filename = here("products", "plots", "candidates_classification.png"),
       p_cand, width = 9, height=3)

# Combine figures
library(magick)
library(patchwork)
f1 <- magick::image_read(here("products", "plots", "biorender_plant_defense_to_pests.png"))
f2 <- magick::image_read(here("products", "plots", "candidates_classification.png"))

final_fig <- image_append(c(image_scale(f1, "2700x2020!"), f2), 
                          stack=TRUE)
magick::image_write(final_fig, 
                    path = here("products", "plots", "candidates_classification_final.png"))
```

Show candidates in a Venn Diagram.

```{r venn_plot}
# Load data
load(here("products", "result_files", "aglycines_minedcand.rda"))
load(here("products", "result_files", "hglycines_minedcand.rda"))
load(here("products", "result_files", "slitura_minedcand.rda"))


venn_pdata <- list(
  Aglycines = unique(mining_aglycines$gene),
  Slitura = unique(mining_slitura$gene),
  Hglycines = unique(mining_hglycines$gene)
)

# Plot venn diagram using the VennDiagram package
library(VennDiagram)
venn.diagram(
        x = venn_pdata,
        category.names = c("A. glycines", "S. litura", "H. glycines"),
        filename = here("products", "plots", "venn_diagram_candidates.png"),
        output=TRUE,
        
        # Output features
        imagetype="png" ,
        height = 1600, 
        width = 1600, 
        resolution = 600,
        
        # Circles
        lwd = 2,
        lty = 'blank',
        fill = c("darkgoldenrod3", "darkgreen", "dimgrey"),
        
        # Numbers
        cex = 0.5,
        fontface = "bold",
        fontfamily = "sans",
        
        # Set names
        cat.cex = 0.5,
        cat.fontface = "italic",
        cat.default.pos = "outer",
        cat.fontfamily = "sans",
        margin = 0.2
)
```

## Comparing to fungi resistance-related genes

```{r}
cgregata <- paste0(tempdir(), "/cgregata.rda")
download.file("https://github.com/almeidasilvaf/SoyFungi_GWAS_GCN/blob/main/products/result_files/cgregata_minedcand.rda?raw=true", destfile = cgregata)

fgraminearum <- paste0(tempdir(), "/fgraminearum.rda")
download.file("https://github.com/almeidasilvaf/SoyFungi_GWAS_GCN/blob/main/products/result_files/fgraminearum_minedcand.rda?raw=true", destfile = fgraminearum)

fvirguliforme <- paste0(tempdir(), "/fvirguliforme.rda")
download.file("https://github.com/almeidasilvaf/SoyFungi_GWAS_GCN/blob/main/products/result_files/fvirguliforme_minedcand.rda?raw=true", destfile = fvirguliforme)

mphaseolina <- paste0(tempdir(), "/mphaseolina.rda")
download.file("https://github.com/almeidasilvaf/SoyFungi_GWAS_GCN/blob/main/products/result_files/mphaseolina_minedcand.rda?raw=true", destfile = mphaseolina)

ppachyrhizi <- paste0(tempdir(), "/ppachyrhizi.rda")
download.file("https://github.com/almeidasilvaf/SoyFungi_GWAS_GCN/blob/main/products/result_files/ppachyrhizi_minedcand.rda?raw=true", destfile = ppachyrhizi)


load(cgregata)
load(fgraminearum)
load(fvirguliforme)
load(mphaseolina)
load(ppachyrhizi)

venn_pdata_comp <- list(
  Aglycines = unique(mining_aglycines$gene),
  Slitura = unique(mining_slitura$gene),
  Hglycines = unique(mining_hglycines$gene),
  Cgregata = unique(mining_cgregata$gene),
  Fgraminearum = unique(mining_fgraminearum$gene),
  Fvirguliforme = unique(mining_fvirguliforme$gene),
  Mphaseolina = unique(mining_mphaseolina$gene),
  Ppachyrhizi = unique(mining_ppachyrhizi$gene)
)

# Plot venn diagram using the VennDiagram package
library(ComplexHeatmap)
upset_matrix <- make_comb_mat(list_to_matrix(venn_pdata_comp))

ht <- draw(
  UpSet(
    upset_matrix,
    set_order = c("Hglycines", "Aglycines", "Slitura",
                  "Fvirguliforme", "Fgraminearum", "Cgregata",
                  "Mphaseolina", "Ppachyrhizi")
  )
)
od <- column_order(ht)
cs <- comb_size(upset_matrix)
decorate_annotation("intersection_size", {
    grid.text(cs[od], x = seq_along(cs), y = unit(cs[od], "native") + unit(2, "pt"), 
        default.units = "native", just = "bottom", gp = gpar(fontsize = 8))
})
# Saved as PDF, 6 x 5 inches
```

## Session information

This document was created under the following conditions:

```{r session_info} 
sessionInfo()
```



